-- ============================================================
-- Phoneme Similarity Project: Database Schema
-- ============================================================
-- Target: SQLite 3.x
-- Author: [Your Name]
-- Date: [Autogenerated by ChatGPT, YYYY-MM-DD]
--
-- This schema stores the CMU Pronouncing Dictionary data along with
-- precomputed phonetic, orthographic, and statistical features for
-- efficient similarity and distance computations in C++.
-- ============================================================

PRAGMA foreign_keys = ON;
PRAGMA synchronous = OFF;
PRAGMA journal_mode = WAL;
PRAGMA journal_mode = MEMORY;
PRAGMA temp_store = MEMORY;

-- ============================================================
-- TABLE: phonemes
-- ============================================================
-- One row per ARPAbet phoneme.
-- Each phoneme is annotated with its articulatory features,
-- stored both as individual numeric columns and as a JSON vector.
-- ============================================================

CREATE TABLE IF NOT EXISTS phonemes (
    phoneme TEXT PRIMARY KEY,
    is_vowel INTEGER NOT NULL,

    -- vowel columns (nullable for consonants)
    height REAL,        --  0 = Low [Open], 0.5 = Mid, 1 = High [Close]
    backness REAL,      --  0 = Front,  0.5 = Central, 1 = Back
    roundness REAL,     --  0 = Rounded, 1 = Unrounded
    
    -- consonant columns (nullable for vowels)
    place REAL,         -- 0 = Bilabial, 0.2 = Labiodental, 0.4 = Dental, 0.6 = Alveolar, 0.8 = Velar, 1 = Glottal
    manner REAL,        -- 0 = Stop, 0.125 = Affricate, 0.25 = Fricative, 0.5 = Nasal, 0.75 = Lateral Liquid, 0.875 = Rhotic Liquid, 1 = Glide
    voicing REAL,       -- 0 = Voiceless, 1 = Voiced

    feature_vector JSON    -- e.g. '[1, 0.5, 0, 0.75, 0.8, 1]'
);

CREATE INDEX IF NOT EXISTS idx_phonemes_is_vowel ON phonemes(is_vowel);
CREATE INDEX IF NOT EXISTS idx_phonemes_is_consonant ON phonemes(NOT is_vowel);



-- ============================================================
-- TABLE: words
-- ============================================================
-- Stores all CMU dictionary entries with rich precomputed metadata.
-- Each row represents one pronunciation of a word (so "READ" appears twice).
-- ============================================================

CREATE TABLE IF NOT EXISTS words (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    word TEXT NOT NULL,                        -- e.g. 'BANANA'
    lemma TEXT,                                -- base form of the word
    cmu_pron_index INTEGER NOT NULL DEFAULT 0, -- index for multiple pronunciations

    phoneme_list TEXT NOT NULL,                -- e.g. 'B AH0 N AE1 N AH0'
    normalized_phoneme_list TEXT NOT NULL,     -- e.g. 'B AH N AE N AH' (stress removed)

    phoneme_count INTEGER NOT NULL,            -- number of phonemes
    unique_phoneme_count INTEGER NOT NULL,     -- distinct phonemes in pronunciation
    num_syllables INTEGER NOT NULL,            -- vowel group count

    primary_stress_index INTEGER,              -- zero-based index of primary stressed vowel
    stress_pattern TEXT,                       -- e.g. '010' for 'banana'

    word_length INTEGER NOT NULL,              -- number of letters
    orth_vowel_count INTEGER NOT NULL,         -- number of vowel letters (a,e,i,o,u,y)
    orth_consonant_count INTEGER NOT NULL,     -- number of consonant letters (all other letters)
    phon_vowel_count INTEGER NOT NULL,         -- number of vowel phonemes
    phon_consonant_count INTEGER NOT NULL,     -- number of consonant phonemes

    orth_vowel_consonant_ratio REAL,           -- vowel_count / consonant_count (orthographic)
    phon_vowel_consonant_ratio REAL,           -- vowel_count / consonant_count (phonetic) 
    grapheme_to_phoneme_ratio REAL,            -- word_length / phoneme_count

    avg_vowel_height REAL,                     -- average vowel features across all vowels in pronunciation
    avg_vowel_backness REAL,                   -- average vowel backness
    avg_vowel_roundness REAL,                  -- average vowel roundness
    avg_consonant_voicing REAL,                -- average consonant features across all consonants
    avg_consonant_place REAL,                  -- average consonant place
    avg_consonant_manner REAL,                 -- average consonant manner

    sonority_profile TEXT,                     -- optional sonority sequence, e.g. '[1,3,4,5,4,1]'
    sonority_rise_count INTEGER,               -- count of sonority rises
    sonority_fall_count INTEGER,               -- count of sonority falls

    word_frequency REAL,                       -- optional (from external corpus)
    phonotactic_probability REAL,              -- optional (from phoneme-level n-gram model)

    source TEXT DEFAULT 'CMUdict-0.7b'

    -- NOTE: The following foreign key is invalid because `words.word` is not
    -- a PRIMARY KEY or UNIQUE column (words can have multiple pronunciations).
    -- Commenting it out to avoid "foreign key mismatch" errors during bulk inserts.
    -- CONSTRAINT fk_lemma FOREIGN KEY (lemma) REFERENCES words(word)
    --     ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_words_word ON words(word);
CREATE INDEX IF NOT EXISTS idx_words_lemma ON words(lemma);
CREATE INDEX IF NOT EXISTS idx_words_length ON words(word_length);
CREATE INDEX IF NOT EXISTS idx_words_syllables ON words(num_syllables);

-- ============================================================
-- TABLE: word_pairs (optional precomputed distances)
-- ============================================================
-- Stores precomputed pairwise distances between words for quick lookup.
-- Use this if you plan to cache edit distances or phonetic similarity scores.
-- ============================================================

-- CREATE TABLE IF NOT EXISTS word_pairs (
--     word_id_1 INTEGER NOT NULL,
--     word_id_2 INTEGER NOT NULL,
-- 
--     phoneme_distance REAL,         -- Levenshtein or feature-based distance
--     feature_distance REAL,         -- optional: aggregate of phoneme feature differences
--     total_distance REAL,           -- combined or weighted metric
-- 
--     PRIMARY KEY (word_id_1, word_id_2),
-- 
--     FOREIGN KEY (word_id_1) REFERENCES words(id) ON DELETE CASCADE,
--     FOREIGN KEY (word_id_2) REFERENCES words(id) ON DELETE CASCADE
-- );

-- ============================================================
-- INDEXES for faster lookup
-- ============================================================



-- CREATE INDEX IF NOT EXISTS idx_word_pairs_distance ON word_pairs(total_distance);

-- ============================================================
-- END OF SCHEMA
-- ============================================================
